name: auth0/auth0-java/build-and-test

on:
  pull_request:
  merge_group:
  push:
    branches: ["master", "main", "v1"]

jobs:
  gradle:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@04b20c065cf1ab708c96e64a8811018d0a1fbc88
        with:
          arguments: assemble check jacocoTestReport --continue --console=plain
      - uses: codecov/codecov-action@e28ff129e5465c2c0dcc6f003fc735cb6ae0c673
        with:
          flags: unittests
      - uses: actions/upload-artifact@v4
        with:
          name: Reports
          path: build/reports
