name: "Validate Gradle Wrapper"
on: [push, pull_request]

jobs:
  validation:
    name: "validation/gradlew"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@9ba54b687bf0f59b62abbf91e0d60de082e8ebc4 # pin@3.4.1
